# RaiderWorld Configuration
# Большинство настроек можно менять командами /raid settings ...

settings:
  waves: 6
  interval-days: 5
  force-night: true
  radius: 50
  difficulty: HARD
  allow-cancel: false

mobs:
  zombie:
    min-wave: 1
    min-count: 20
    max-count: 40
    armor-chance: 40
    weapon-chance: 15
    incomplete-armor-chance: 30
  skeleton:
    min-wave: 1
    min-count: 5
    max-count: 15
    armor-chance: 25
    weapon-chance: 80
    incomplete-armor-chance: 20
  husk:
    min-wave: 2
    min-count: 5
    max-count: 20
    armor-chance: 30
    weapon-chance: 10
    incomplete-armor-chance: 25

# Фиксированная точка спавна рейда (устанавливается /raid setspawn)
# spawn:
#   world: world
#   x: 0
#   y: 64
#   z: 0
