name: TeleportMenu
version: 1.0.0
main: ru.mineseason.teleportmenu.TeleportMenu
api-version: '26.1'

commands:
  teleportmenu:
    description: Выдать предмет телепортации
    usage: /teleportmenu
    permission: teleportmenu.give

permissions:
  teleportmenu.give:
    default: op