name: TeleportMenu
version: 3.0.0
main: ru.mineseason.teleportmenu.TeleportMenu
api-version: '1.21'
author: Sergey
description: Teleportation menu with players, spawn and saved position
commands:
  tpmenu:
    description: Main TeleportMenu command
    usage: /tpmenu
    permission: teleportmenu.use
permissions:
  teleportmenu.use:
    description: Allows using the teleport menu
    default: true
  teleportmenu.admin:
    description: Allows managing players and saved position
    default: op